On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bower_components/angular-animate/LICENSE.md
	bower_components/angular-aria/LICENSE.md
	bower_components/angular-bootstrap/ui-bootstrap-csp.css
	bower_components/angular-material/angular-material.css
	bower_components/angular-material/angular-material.min.css
	bower_components/angular-material/layouts/angular-material.layout-attributes.css
	bower_components/angular-material/layouts/angular-material.layout-attributes.min.css
	bower_components/angular-material/layouts/angular-material.layouts.css
	bower_components/angular-material/layouts/angular-material.layouts.ie_fixes.css
	bower_components/angular-material/layouts/angular-material.layouts.min.css
	bower_components/angular-material/modules/closure/autocomplete/autocomplete-default-theme.css
	bower_components/angular-material/modules/closure/autocomplete/autocomplete-default-theme.min.css
	bower_components/angular-material/modules/closure/autocomplete/autocomplete.css
	bower_components/angular-material/modules/closure/autocomplete/autocomplete.min.css
	bower_components/angular-material/modules/closure/backdrop/backdrop-default-theme.css
	bower_components/angular-material/modules/closure/backdrop/backdrop-default-theme.min.css
	bower_components/angular-material/modules/closure/backdrop/backdrop.css
	bower_components/angular-material/modules/closure/backdrop/backdrop.min.css
	bower_components/angular-material/modules/closure/bottomSheet/bottomSheet-default-theme.css
	bower_components/angular-material/modules/closure/bottomSheet/bottomSheet-default-theme.min.css
	bower_components/angular-material/modules/closure/bottomSheet/bottomSheet.css
	bower_components/angular-material/modules/closure/bottomSheet/bottomSheet.min.css
	bower_components/angular-material/modules/closure/button/button-default-theme.css
	bower_components/angular-material/modules/closure/button/button-default-theme.min.css
	bower_components/angular-material/modules/closure/button/button.css
	bower_components/angular-material/modules/closure/button/button.min.css
	bower_components/angular-material/modules/closure/card/card-default-theme.css
	bower_components/angular-material/modules/closure/card/card-default-theme.min.css
	bower_components/angular-material/modules/closure/card/card.css
	bower_components/angular-material/modules/closure/card/card.min.css
	bower_components/angular-material/modules/closure/checkbox/checkbox-default-theme.css
	bower_components/angular-material/modules/closure/checkbox/checkbox-default-theme.min.css
	bower_components/angular-material/modules/closure/checkbox/checkbox.css
	bower_components/angular-material/modules/closure/checkbox/checkbox.min.css
	bower_components/angular-material/modules/closure/chips/chips-default-theme.css
	bower_components/angular-material/modules/closure/chips/chips-default-theme.min.css
	bower_components/angular-material/modules/closure/chips/chips.css
	bower_components/angular-material/modules/closure/chips/chips.min.css
	bower_components/angular-material/modules/closure/content/content-default-theme.css
	bower_components/angular-material/modules/closure/content/content-default-theme.min.css
	bower_components/angular-material/modules/closure/content/content.css
	bower_components/angular-material/modules/closure/content/content.min.css
	bower_components/angular-material/modules/closure/core/core-default-theme.css
	bower_components/angular-material/modules/closure/core/core-default-theme.min.css
	bower_components/angular-material/modules/closure/core/core.css
	bower_components/angular-material/modules/closure/core/core.min.css
	bower_components/angular-material/modules/closure/datepicker/datepicker-default-theme.css
	bower_components/angular-material/modules/closure/datepicker/datepicker-default-theme.min.css
	bower_components/angular-material/modules/closure/datepicker/datepicker.css
	bower_components/angular-material/modules/closure/datepicker/datepicker.min.css
	bower_components/angular-material/modules/closure/dialog/dialog-default-theme.css
	bower_components/angular-material/modules/closure/dialog/dialog-default-theme.min.css
	bower_components/angular-material/modules/closure/dialog/dialog.css
	bower_components/angular-material/modules/closure/dialog/dialog.min.css
	bower_components/angular-material/modules/closure/divider/divider-default-theme.css
	bower_components/angular-material/modules/closure/divider/divider-default-theme.min.css
	bower_components/angular-material/modules/closure/divider/divider.css
	bower_components/angular-material/modules/closure/divider/divider.min.css
	bower_components/angular-material/modules/closure/fabSpeedDial/fabSpeedDial.css
	bower_components/angular-material/modules/closure/fabSpeedDial/fabSpeedDial.min.css
	bower_components/angular-material/modules/closure/fabToolbar/fabToolbar.css
	bower_components/angular-material/modules/closure/fabToolbar/fabToolbar.min.css
	bower_components/angular-material/modules/closure/gridList/gridList-default-theme.css
	bower_components/angular-material/modules/closure/gridList/gridList.css
	bower_components/angular-material/modules/closure/gridList/gridList.min.css
	bower_components/angular-material/modules/closure/icon/icon-default-theme.css
	bower_components/angular-material/modules/closure/icon/icon-default-theme.min.css
	bower_components/angular-material/modules/closure/icon/icon.css
	bower_components/angular-material/modules/closure/icon/icon.min.css
	bower_components/angular-material/modules/closure/input/input-default-theme.css
	bower_components/angular-material/modules/closure/input/input-default-theme.min.css
	bower_components/angular-material/modules/closure/input/input.css
	bower_components/angular-material/modules/closure/input/input.min.css
	bower_components/angular-material/modules/closure/list/list-default-theme.css
	bower_components/angular-material/modules/closure/list/list-default-theme.min.css
	bower_components/angular-material/modules/closure/list/list.css
	bower_components/angular-material/modules/closure/list/list.min.css
	bower_components/angular-material/modules/closure/menu/menu-default-theme.css
	bower_components/angular-material/modules/closure/menu/menu-default-theme.min.css
	bower_components/angular-material/modules/closure/menu/menu.css
	bower_components/angular-material/modules/closure/menu/menu.min.css
	bower_components/angular-material/modules/closure/menuBar/menuBar-default-theme.css
	bower_components/angular-material/modules/closure/menuBar/menuBar-default-theme.min.css
	bower_components/angular-material/modules/closure/menuBar/menuBar.css
	bower_components/angular-material/modules/closure/menuBar/menuBar.min.css
	bower_components/angular-material/modules/closure/navBar/navBar-default-theme.css
	bower_components/angular-material/modules/closure/navBar/navBar-default-theme.min.css
	bower_components/angular-material/modules/closure/navBar/navBar.css
	bower_components/angular-material/modules/closure/navBar/navBar.min.css
	bower_components/angular-material/modules/closure/panel/panel-default-theme.css
	bower_components/angular-material/modules/closure/panel/panel-default-theme.min.css
	bower_components/angular-material/modules/closure/panel/panel.css
	bower_components/angular-material/modules/closure/panel/panel.min.css
	bower_components/angular-material/modules/closure/progressCircular/progressCircular-default-theme.css
	bower_components/angular-material/modules/closure/progressCircular/progressCircular-default-theme.min.css
	bower_components/angular-material/modules/closure/progressCircular/progressCircular.css
	bower_components/angular-material/modules/closure/progressCircular/progressCircular.min.css
	bower_components/angular-material/modules/closure/progressLinear/progressLinear-default-theme.css
	bower_components/angular-material/modules/closure/progressLinear/progressLinear-default-theme.min.css
	bower_components/angular-material/modules/closure/progressLinear/progressLinear.css
	bower_components/angular-material/modules/closure/progressLinear/progressLinear.min.css
	bower_components/angular-material/modules/closure/radioButton/radioButton-default-theme.css
	bower_components/angular-material/modules/closure/radioButton/radioButton-default-theme.min.css
	bower_components/angular-material/modules/closure/radioButton/radioButton.css
	bower_components/angular-material/modules/closure/radioButton/radioButton.min.css
	bower_components/angular-material/modules/closure/select/select-default-theme.css
	bower_components/angular-material/modules/closure/select/select-default-theme.min.css
	bower_components/angular-material/modules/closure/select/select.css
	bower_components/angular-material/modules/closure/select/select.min.css
	bower_components/angular-material/modules/closure/sidenav/sidenav-default-theme.css
	bower_components/angular-material/modules/closure/sidenav/sidenav-default-theme.min.css
	bower_components/angular-material/modules/closure/sidenav/sidenav.css
	bower_components/angular-material/modules/closure/sidenav/sidenav.min.css
	bower_components/angular-material/modules/closure/slider/slider-default-theme.css
	bower_components/angular-material/modules/closure/slider/slider-default-theme.min.css
	bower_components/angular-material/modules/closure/slider/slider.css
	bower_components/angular-material/modules/closure/slider/slider.min.css
	bower_components/angular-material/modules/closure/sticky/sticky.css
	bower_components/angular-material/modules/closure/sticky/sticky.min.css
	bower_components/angular-material/modules/closure/subheader/subheader-default-theme.css
	bower_components/angular-material/modules/closure/subheader/subheader-default-theme.min.css
	bower_components/angular-material/modules/closure/subheader/subheader.css
	bower_components/angular-material/modules/closure/subheader/subheader.min.css
	bower_components/angular-material/modules/closure/switch/switch-default-theme.css
	bower_components/angular-material/modules/closure/switch/switch-default-theme.min.css
	bower_components/angular-material/modules/closure/switch/switch.css
	bower_components/angular-material/modules/closure/switch/switch.min.css
	bower_components/angular-material/modules/closure/tabs/tabs-default-theme.css
	bower_components/angular-material/modules/closure/tabs/tabs-default-theme.min.css
	bower_components/angular-material/modules/closure/tabs/tabs.css
	bower_components/angular-material/modules/closure/tabs/tabs.min.css
	bower_components/angular-material/modules/closure/textField/textField-default-theme.css
	bower_components/angular-material/modules/closure/textField/textField.css
	bower_components/angular-material/modules/closure/toast/toast-default-theme.css
	bower_components/angular-material/modules/closure/toast/toast-default-theme.min.css
	bower_components/angular-material/modules/closure/toast/toast.css
	bower_components/angular-material/modules/closure/toast/toast.min.css
	bower_components/angular-material/modules/closure/toolbar/toolbar-default-theme.css
	bower_components/angular-material/modules/closure/toolbar/toolbar-default-theme.min.css
	bower_components/angular-material/modules/closure/toolbar/toolbar.css
	bower_components/angular-material/modules/closure/toolbar/toolbar.min.css
	bower_components/angular-material/modules/closure/tooltip/tooltip-default-theme.css
	bower_components/angular-material/modules/closure/tooltip/tooltip-default-theme.min.css
	bower_components/angular-material/modules/closure/tooltip/tooltip.css
	bower_components/angular-material/modules/closure/tooltip/tooltip.min.css
	bower_components/angular-material/modules/closure/truncate/truncate.css
	bower_components/angular-material/modules/closure/truncate/truncate.min.css
	bower_components/angular-material/modules/closure/virtualRepeat/virtualRepeat.css
	bower_components/angular-material/modules/closure/virtualRepeat/virtualRepeat.min.css
	bower_components/angular-material/modules/closure/whiteframe/whiteframe.css
	bower_components/angular-material/modules/closure/whiteframe/whiteframe.min.css
	bower_components/angular-material/modules/js/autocomplete/autocomplete-default-theme.css
	bower_components/angular-material/modules/js/autocomplete/autocomplete-default-theme.min.css
	bower_components/angular-material/modules/js/autocomplete/autocomplete.css
	bower_components/angular-material/modules/js/autocomplete/autocomplete.min.css
	bower_components/angular-material/modules/js/backdrop/backdrop-default-theme.css
	bower_components/angular-material/modules/js/backdrop/backdrop-default-theme.min.css
	bower_components/angular-material/modules/js/backdrop/backdrop.css
	bower_components/angular-material/modules/js/backdrop/backdrop.min.css
	bower_components/angular-material/modules/js/bottomSheet/bottomSheet-default-theme.css
	bower_components/angular-material/modules/js/bottomSheet/bottomSheet-default-theme.min.css
	bower_components/angular-material/modules/js/bottomSheet/bottomSheet.css
	bower_components/angular-material/modules/js/bottomSheet/bottomSheet.min.css
	bower_components/angular-material/modules/js/button/button-default-theme.css
	bower_components/angular-material/modules/js/button/button-default-theme.min.css
	bower_components/angular-material/modules/js/button/button.css
	bower_components/angular-material/modules/js/button/button.min.css
	bower_components/angular-material/modules/js/card/card-default-theme.css
	bower_components/angular-material/modules/js/card/card-default-theme.min.css
	bower_components/angular-material/modules/js/card/card.css
	bower_components/angular-material/modules/js/card/card.min.css
	bower_components/angular-material/modules/js/checkbox/checkbox-default-theme.css
	bower_components/angular-material/modules/js/checkbox/checkbox-default-theme.min.css
	bower_components/angular-material/modules/js/checkbox/checkbox.css
	bower_components/angular-material/modules/js/checkbox/checkbox.min.css
	bower_components/angular-material/modules/js/chips/chips-default-theme.css
	bower_components/angular-material/modules/js/chips/chips-default-theme.min.css
	bower_components/angular-material/modules/js/chips/chips.css
	bower_components/angular-material/modules/js/chips/chips.min.css
	bower_components/angular-material/modules/js/content/content-default-theme.css
	bower_components/angular-material/modules/js/content/content-default-theme.min.css
	bower_components/angular-material/modules/js/content/content.css
	bower_components/angular-material/modules/js/content/content.min.css
	bower_components/angular-material/modules/js/core/core-default-theme.css
	bower_components/angular-material/modules/js/core/core-default-theme.min.css
	bower_components/angular-material/modules/js/core/core.css
	bower_components/angular-material/modules/js/core/core.min.css
	bower_components/angular-material/modules/js/datepicker/datepicker-default-theme.css
	bower_components/angular-material/modules/js/datepicker/datepicker-default-theme.min.css
	bower_components/angular-material/modules/js/datepicker/datepicker.css
	bower_components/angular-material/modules/js/datepicker/datepicker.min.css
	bower_components/angular-material/modules/js/dialog/dialog-default-theme.css
	bower_components/angular-material/modules/js/dialog/dialog-default-theme.min.css
	bower_components/angular-material/modules/js/dialog/dialog.css
	bower_components/angular-material/modules/js/dialog/dialog.min.css
	bower_components/angular-material/modules/js/divider/divider-default-theme.css
	bower_components/angular-material/modules/js/divider/divider-default-theme.min.css
	bower_components/angular-material/modules/js/divider/divider.css
	bower_components/angular-material/modules/js/divider/divider.min.css
	bower_components/angular-material/modules/js/fabSpeedDial/fabSpeedDial.css
	bower_components/angular-material/modules/js/fabSpeedDial/fabSpeedDial.min.css
	bower_components/angular-material/modules/js/fabToolbar/fabToolbar.css
	bower_components/angular-material/modules/js/fabToolbar/fabToolbar.min.css
	bower_components/angular-material/modules/js/gridList/gridList.css
	bower_components/angular-material/modules/js/gridList/gridList.min.css
	bower_components/angular-material/modules/js/icon/icon-default-theme.css
	bower_components/angular-material/modules/js/icon/icon-default-theme.min.css
	bower_components/angular-material/modules/js/icon/icon.css
	bower_components/angular-material/modules/js/icon/icon.min.css
	bower_components/angular-material/modules/js/input/input-default-theme.css
	bower_components/angular-material/modules/js/input/input-default-theme.min.css
	bower_components/angular-material/modules/js/input/input.css
	bower_components/angular-material/modules/js/input/input.min.css
	bower_components/angular-material/modules/js/list/list-default-theme.css
	bower_components/angular-material/modules/js/list/list-default-theme.min.css
	bower_components/angular-material/modules/js/list/list.css
	bower_components/angular-material/modules/js/list/list.min.css
	bower_components/angular-material/modules/js/menu/menu-default-theme.css
	bower_components/angular-material/modules/js/menu/menu-default-theme.min.css
	bower_components/angular-material/modules/js/menu/menu.css
	bower_components/angular-material/modules/js/menu/menu.min.css
	bower_components/angular-material/modules/js/menuBar/menuBar-default-theme.css
	bower_components/angular-material/modules/js/menuBar/menuBar-default-theme.min.css
	bower_components/angular-material/modules/js/menuBar/menuBar.css
	bower_components/angular-material/modules/js/menuBar/menuBar.min.css
	bower_components/angular-material/modules/js/navBar/navBar-default-theme.css
	bower_components/angular-material/modules/js/navBar/navBar-default-theme.min.css
	bower_components/angular-material/modules/js/navBar/navBar.css
	bower_components/angular-material/modules/js/navBar/navBar.min.css
	bower_components/angular-material/modules/js/panel/panel-default-theme.css
	bower_components/angular-material/modules/js/panel/panel-default-theme.min.css
	bower_components/angular-material/modules/js/panel/panel.css
	bower_components/angular-material/modules/js/panel/panel.min.css
	bower_components/angular-material/modules/js/progressCircular/progressCircular-default-theme.css
	bower_components/angular-material/modules/js/progressCircular/progressCircular-default-theme.min.css
	bower_components/angular-material/modules/js/progressCircular/progressCircular.css
	bower_components/angular-material/modules/js/progressCircular/progressCircular.min.css
	bower_components/angular-material/modules/js/progressLinear/progressLinear-default-theme.css
	bower_components/angular-material/modules/js/progressLinear/progressLinear-default-theme.min.css
	bower_components/angular-material/modules/js/progressLinear/progressLinear.css
	bower_components/angular-material/modules/js/progressLinear/progressLinear.min.css
	bower_components/angular-material/modules/js/radioButton/radioButton-default-theme.css
	bower_components/angular-material/modules/js/radioButton/radioButton-default-theme.min.css
	bower_components/angular-material/modules/js/radioButton/radioButton.css
	bower_components/angular-material/modules/js/radioButton/radioButton.min.css
	bower_components/angular-material/modules/js/select/select-default-theme.css
	bower_components/angular-material/modules/js/select/select-default-theme.min.css
	bower_components/angular-material/modules/js/select/select.css
	bower_components/angular-material/modules/js/select/select.min.css
	bower_components/angular-material/modules/js/sidenav/sidenav-default-theme.css
	bower_components/angular-material/modules/js/sidenav/sidenav-default-theme.min.css
	bower_components/angular-material/modules/js/sidenav/sidenav.css
	bower_components/angular-material/modules/js/sidenav/sidenav.min.css
	bower_components/angular-material/modules/js/slider/slider-default-theme.css
	bower_components/angular-material/modules/js/slider/slider-default-theme.min.css
	bower_components/angular-material/modules/js/slider/slider.css
	bower_components/angular-material/modules/js/slider/slider.min.css
	bower_components/angular-material/modules/js/sticky/sticky.css
	bower_components/angular-material/modules/js/sticky/sticky.min.css
	bower_components/angular-material/modules/js/subheader/subheader-default-theme.css
	bower_components/angular-material/modules/js/subheader/subheader-default-theme.min.css
	bower_components/angular-material/modules/js/subheader/subheader.css
	bower_components/angular-material/modules/js/subheader/subheader.min.css
	bower_components/angular-material/modules/js/switch/switch-default-theme.css
	bower_components/angular-material/modules/js/switch/switch-default-theme.min.css
	bower_components/angular-material/modules/js/switch/switch.css
	bower_components/angular-material/modules/js/switch/switch.min.css
	bower_components/angular-material/modules/js/tabs/tabs-default-theme.css
	bower_components/angular-material/modules/js/tabs/tabs-default-theme.min.css
	bower_components/angular-material/modules/js/tabs/tabs.css
	bower_components/angular-material/modules/js/tabs/tabs.min.css
	bower_components/angular-material/modules/js/textField/textField-default-theme.css
	bower_components/angular-material/modules/js/textField/textField-default-theme.min.css
	bower_components/angular-material/modules/js/textField/textField.css
	bower_components/angular-material/modules/js/textField/textField.min.css
	bower_components/angular-material/modules/js/toast/toast-default-theme.css
	bower_components/angular-material/modules/js/toast/toast-default-theme.min.css
	bower_components/angular-material/modules/js/toast/toast.css
	bower_components/angular-material/modules/js/toast/toast.min.css
	bower_components/angular-material/modules/js/toolbar/toolbar-default-theme.css
	bower_components/angular-material/modules/js/toolbar/toolbar-default-theme.min.css
	bower_components/angular-material/modules/js/toolbar/toolbar.css
	bower_components/angular-material/modules/js/toolbar/toolbar.min.css
	bower_components/angular-material/modules/js/tooltip/tooltip-default-theme.css
	bower_components/angular-material/modules/js/tooltip/tooltip-default-theme.min.css
	bower_components/angular-material/modules/js/tooltip/tooltip.css
	bower_components/angular-material/modules/js/tooltip/tooltip.min.css
	bower_components/angular-material/modules/js/truncate/truncate.css
	bower_components/angular-material/modules/js/truncate/truncate.min.css
	bower_components/angular-material/modules/js/virtualRepeat/virtualRepeat.css
	bower_components/angular-material/modules/js/virtualRepeat/virtualRepeat.min.css
	bower_components/angular-material/modules/js/whiteframe/whiteframe.css
	bower_components/angular-material/modules/js/whiteframe/whiteframe.min.css
	bower_components/angular-material/modules/layouts/
	bower_components/angular-messages/LICENSE.md
	bower_components/angular-mocks/LICENSE.md
	bower_components/angular-route/LICENSE.md
	bower_components/angular-sanitize/LICENSE.md
	bower_components/angular-touch/LICENSE.md
	bower_components/angular/LICENSE.md
	bower_components/angular/angular-csp.css
	bower_components/animate.css/
	bower_components/bootstrap/Gemfile
	bower_components/bootstrap/Gemfile.lock
	bower_components/bootstrap/ISSUE_TEMPLATE.md
	bower_components/bootstrap/grunt/change-version.js
	bower_components/bootstrap/grunt/npm-shrinkwrap.json
	bower_components/bootstrap/less/bootstrap.css
	bower_components/bootstrap/less/media.css
	bower_components/bootstrap/less/mixins.css
	bower_components/bootstrap/less/mixins/alerts.css
	bower_components/bootstrap/less/mixins/background-variant.css
	bower_components/bootstrap/less/mixins/border-radius.css
	bower_components/bootstrap/less/mixins/buttons.css
	bower_components/bootstrap/less/mixins/center-block.css
	bower_components/bootstrap/less/mixins/clearfix.css
	bower_components/bootstrap/less/mixins/forms.css
	bower_components/bootstrap/less/mixins/gradients.css
	bower_components/bootstrap/less/mixins/grid-framework.css
	bower_components/bootstrap/less/mixins/grid.css
	bower_components/bootstrap/less/mixins/hide-text.css
	bower_components/bootstrap/less/mixins/image.css
	bower_components/bootstrap/less/mixins/labels.css
	bower_components/bootstrap/less/mixins/list-group.css
	bower_components/bootstrap/less/mixins/nav-divider.css
	bower_components/bootstrap/less/mixins/nav-vertical-align.css
	bower_components/bootstrap/less/mixins/opacity.css
	bower_components/bootstrap/less/mixins/pagination.css
	bower_components/bootstrap/less/mixins/panels.css
	bower_components/bootstrap/less/mixins/progress-bar.css
	bower_components/bootstrap/less/mixins/reset-filter.css
	bower_components/bootstrap/less/mixins/reset-text.css
	bower_components/bootstrap/less/mixins/resize.css
	bower_components/bootstrap/less/mixins/responsive-visibility.css
	bower_components/bootstrap/less/mixins/size.css
	bower_components/bootstrap/less/mixins/tab-focus.css
	bower_components/bootstrap/less/mixins/table-row.css
	bower_components/bootstrap/less/mixins/text-emphasis.css
	bower_components/bootstrap/less/mixins/text-overflow.css
	bower_components/bootstrap/less/mixins/vendor-prefixes.css
	bower_components/bootstrap/less/normalize.css
	bower_components/bootstrap/less/print.css
	bower_components/bootstrap/less/responsive-embed.css
	bower_components/bootstrap/less/theme.css
	bower_components/bootstrap/less/variables.css
	bower_components/font-awesome/css/font-awesome.css
	bower_components/font-awesome/css/font-awesome.min.css
	bower_components/font-awesome/less/font-awesome.css
	bower_components/font-awesome/less/mixins.css
	bower_components/font-awesome/less/screen-reader.less
	bower_components/font-awesome/less/variables.css
	bower_components/font-awesome/scss/_screen-reader.scss
	bower_components/jquery/external/
	bower_components/jquery/src/.eslintrc.json
	bower_components/jquery/src/core/nodeName.js
	bower_components/jquery/src/core/ready-no-deferred.js
	bower_components/jquery/src/core/readyException.js
	bower_components/jquery/src/core/stripAndCollapse.js
	bower_components/jquery/src/css/var/isHiddenWithinTree.js
	bower_components/jquery/src/var/ObjectFunctionString.js
	bower_components/jquery/src/var/fnToString.js
	bower_components/jquery/src/var/getProto.js
	bower_components/jquery/src/var/rnothtmlwhite.js
	bower_components/ui-bootstrap/misc/demo/assets/demo.css
	bower_components/ui-bootstrap/misc/demo/assets/rainbow.css
	bower_components/ui-bootstrap/src/carousel/carousel.css
	bower_components/ui-bootstrap/src/carousel/index-nocss.js
	bower_components/ui-bootstrap/src/datepicker/datepicker.css
	bower_components/ui-bootstrap/src/datepicker/index-nocss.js
	bower_components/ui-bootstrap/src/datepickerPopup/
	bower_components/ui-bootstrap/src/dropdown/index-nocss.js
	bower_components/ui-bootstrap/src/modal/index-nocss.js
	bower_components/ui-bootstrap/src/popover/index-nocss.js
	bower_components/ui-bootstrap/src/position/index-nocss.js
	bower_components/ui-bootstrap/src/position/position.css
	bower_components/ui-bootstrap/src/timepicker/index-nocss.js
	bower_components/ui-bootstrap/src/timepicker/timepicker.css
	bower_components/ui-bootstrap/src/tooltip/index-nocss.js
	bower_components/ui-bootstrap/src/tooltip/tooltip.css
	bower_components/ui-bootstrap/src/typeahead/index-nocss.js
	bower_components/ui-bootstrap/src/typeahead/typeahead.css
	bower_components/ui-bootstrap/template/datepickerPopup/
	t

no changes added to commit (use "git add" and/or "git commit -a")
